#!/bin/bash

if [ "$(ls -A $ROOT_DIR/service)" ]; then
    echo "$ROOT_DIR/service is not empty!"
    pip3 install -i https://pypi.douban.com/simple -r $ROOT_DIR/service/requirements.txt
else
    echo "$ROOT_DIR/service is empty. "
    tarpit create service
fi

cd $ROOT_DIR/service
tarpit serve